### ISSUE TITLE
bigger emoji list?

### ISSUE THREAD

**Issue by dcsan** [ines/console-dot-emoji#1]
this is fun! but is there a bigger list of emoji somewhere to add to it?

**Comment by ines** [comment]
Thanks! 

And yes – in [console.emoji.js](https://github.com/ines/console-dot-emoji/blob/master/console.emoji.js), simply add to this list and define your own:

```javascript
var commands = [
    [ "unicorn", "🦄" ],
    [ "pizza", "🍕" ],
    [ "beer", "🍺"],
    [ "poo", "💩"]
];
```

You can come up with your own commands and add the emoji of your choice via the keyboard (or copy-paste from a list like [this](http://getemoji.com/)) – no need to encode the unicode character.

**Comment by dcsan** [comment]
where would i retrieve such a list from? most online references I've seen are kind of broken up...

/dc

**Comment by ines** [comment]
This site seems pretty good and complete, and it lets you copy-paste: http://getemoji.com

Or, if you're on a Mac, press ctrl + cmd + space to open the emoji menu (or open it via Edit > Emoji & Symbols). This should also work in your text editor, so you can insert them into the JavaScript straight away 😊

**Comment by dcsan** [comment]
> ctrl + cmd + space to open the emoji menu 

I did not know that and I thought i was a keyboard master! Schooled, thanks!
